In [1]:
# import required libraries
import pandas as pd

In [3]:
# import dataset
data = pd.read_csv("../data/world_population.csv")
data.head()

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00

In [7]:
GR_ds = data[["Country","Continent","Growth Rate"]]
GR_ds.head()

          Country Continent  Growth Rate
0     Afghanistan      Asia       1.0257
1         Albania    Europe       0.9957
2         Algeria    Africa       1.0164
3  American Samoa   Oceania       0.9831
4         Andorra    Europe       1.0100

In [11]:
sorted_GR = GR_ds.sort_values(by=["Growth Rate"],ascending=False)
sorted_GR.head()

      Country Continent  Growth Rate
133   Moldova    Europe       1.0691
164    Poland    Europe       1.0404
148     Niger    Africa       1.0378
202     Syria      Asia       1.0376
189  Slovakia    Europe       1.0359

In [14]:
#export to csv file
sorted_GR.iloc[:11,:].to_csv("../data/Top10Growth_Rate.csv")

In [15]:
#create new dataset for population changes over the years
copy1 = data.copy(deep=True)

copy1["change2022_1970"] = copy1["2022 Population"] - copy1["1970 Population"]

copy1.to_csv("../data/change.csv")

In [14]:
# dataset for line chart

ds_copy = data.copy(deep=True)
grouped = ds_copy.groupby("Continent").mean()
grouped

/var/folders/3v/smc24lcd439c520zdn9htkr80000gn/T/ipykernel_2730/2697936538.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped = ds_copy.groupby("Continent").mean()

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,
Africa,92.157895,2.503037e+07,2.387144e+07,2.107197e+07,1.851277e+07,1.436747e+07,1.119563e+07,8.448007e+06,6.411304e+06,5.318941e+05,125.047646,1.021244,0.313509
Asia,77.560000,9.442767e+07,9.326173e+07,8.916500e+07,8.440083e+07,7.470179e+07,6.421127e+07,5.270668e+07,4.289813e+07,6.427628e+05,1025.024136,1.009384,1.183800
Europe,124.500000,1.486295e+07,1.491584e+07,1.483071e+07,1.471228e+07,1.452187e+07,1.440642e+07,1.385054e+07,1.311848e+07,4.602082e+05,663.324742,1.002256,0.186600
North America,160.925000,1.500740e+07,1.485591e+07,1.425960e+07,1.356802e+07,1.215174e+07,1.053166e+07,9.207334e+06,7.885865e+06,6.061044e+05,272.761758,1.004175,0.187750
Oceania,188.521739,1.958198e+06,1.910149e+06,1.756664e+06,1.613164e+06,1.357512e+06,1.162775e+06,9.965322e+05,8.469683e+05,3.702209e+05,132.543065,1.007383,0.023913
South America,97.571429,3.120119e+07,3.082357e+07,2.950960e+07,2.807702e+07,2.497388e+07,2.122474e+07,1.727064e+07,1.378194e+07,1.273813e+06,20.971979,1.007957,0.391429

In [15]:
grouped.melt(id_vars=["Continent"], var_name="Date",value_name="Value")

KeyError: "The following 'id_vars' are not present in the DataFrame: ['Continent']"